# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

image: Visual Studio 2019

branches:
  only:
    - master

# Perform the build.
build_script:
  - bash build/appveyor.sh

# The tests are run as part of the build.
test: off
