name: Build documentation

on: workflow_dispatch

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out nodatime.org
      uses: actions/checkout@v4
      with:
        path: nodatime.org

    - name: Checkout nodatime
      uses: actions/checkout@v4
      with:
        path: nodatime

    - name: Checkout nodatime.serialization
      uses: actions/checkout@v4
      with:
        path: nodatime.serialization

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Diagnostics
      run: ls

    - name: Docker build
      run: |-
        docker build \
          -f nodatime.org/build/Dockerfile \
          .